select * from customer limit 20
--1. What is the revenue generated by male vs famale customers?
select gender, sum(purchase_amount) as revenue
from customer 
group by gender
--2. which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
--3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Avarage Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
--Compare the average Purchase Amount between Standard and Express Shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in('Standard','Express')
group by shipping_type

--Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

6. which 5 products have the highest percentage of purchases with discount applied
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- 7. Segment customers into new returning, and loyal based on their total number of previous purchase, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment
-- 8. what are the top 3 most purchased products whithin each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category 
                           ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;
-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyears
from customer
where previous_purchases > 5
group by subscription_status

-- 10. what is the revenue contrivution of each age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
